### PR TITLE
Update Gateway.php

### PR DESCRIPTION
**Pull request by alangilby**
Updated Guzzle to 7 for v 3

### CODE REVIEW

**Comment by lukeholder** [comment]
Sorry we had not tagged 3.0.0 of this gateway which had this update to Guzzle 7 on the `develop` branch. Fixed and now released 3.0.0 

Thanks

**Comment by lukeholder** [comment]
Can you please send your composer.lock and composer.json file to us at support@craftcms.com

After that could you try deleting your vendor folder and running `composer install` again?

Will take a look at your composer files asap.

**Comment by alangilby** [comment]
Hey, sorry about this, a local composer cache clear did the trick.
Nice one.

**Comment by nfourtythree** [comment]
Hi @alangilby 

Thank you for letting us know.

We will close this PR.

Thanks!

**Pull request closed without merging**
